### ISSUE TITLE
Generify redis and mail sender

### ISSUE THREAD

**Issue by ocxo** [articulate/shush#32]
Currently tied to redistogo and postmark, we should have these configurable.

**Comment by elyscape** [comment]
Additionally, you're tied to AWS SES for the mailer. It might be a good idea to support generic SMTP (ideally over TLS).

**Comment by fromonesrc** [comment]
Thanks for the suggestion @elyscape :thumbsup:

We switched from Postmark to SES but generic SMTP would be a nice addition. PRs welcome in case you want to tackle that before we can get to it.

**Comment by mloberg** [comment]
Email functionality was removed. Redis should be generic
